basePath: /arkivy/v1.0
definitions:
  game.CreateGameRequest:
    properties:
      amount:
        example: 10
        minimum: 0
        type: integer
      name:
        example: Chess
        type: string
    required:
    - name
    type: object
  game.Game:
    properties:
      amount:
        example: 10
        type: integer
      cAt:
        type: string
      id:
        example: 018f1a2b-3c4d-7e5f-8a9b-0c1d2e3f4a5b
        type: string
      name:
        example: Chess
        type: string
      uAt:
        type: string
    type: object
host: localhost:9090
info:
  contact: {}
  description: API del proyecto Arkivy
  title: Arkivy API
  version: "1.0"
paths:
  /games:
    get:
      description: Retorna todos los juegos disponibles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/game.Game'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Listar juegos
      tags:
      - games
    post:
      consumes:
      - application/json
      description: Crea un nuevo juego en la base de datos
      parameters:
      - description: Datos del juego
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/game.CreateGameRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/game.Game'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Crear un juego
      tags:
      - games
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
